# Generated by Django 4.1.3 on 2024-04-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsummary',
            old_name='haistory',
            new_name='history',
        ),
    ]
